mutation ($username: String, $password: String, $defaultPartnerOtpSend: Boolean) {
  login(username: $username, password: $password, defaultPartnerOtpSend: $defaultPartnerOtpSend) {
    code
    message
  }
}
